version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "05:00"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "uv"
    directory: "/misc/codegen"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "05:00"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "uv"
    directory: "/misc/qt-updater"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "05:00"
    groups:
      dependencies:
        patterns:
          - "*"
